steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/sara-sandbox-interns/bookshelf-repo/bookshelf-app:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'europe-west1-docker.pkg.dev/sara-sandbox-interns/bookshelf-repo/bookshelf-app:$SHORT_SHA'